In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:
data='dataset/iris.csv'
df=pd.read_csv(data)
df.columns =['sep-len', 'sep-wid', 'pet-len', 'pet-wid','class']
print(df)

     sep-len  sep-wid  pet-len  pet-wid           class
0        4.9      3.0      1.4      0.2     Iris-setosa
1        4.7      3.2      1.3      0.2     Iris-setosa
2        4.6      3.1      1.5      0.2     Iris-setosa
3        5.0      3.6      1.4      0.2     Iris-setosa
4        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
144      6.7      3.0      5.2      2.3  Iris-virginica
145      6.3      2.5      5.0      1.9  Iris-virginica
146      6.5      3.0      5.2      2.0  Iris-virginica
147      6.2      3.4      5.4      2.3  Iris-virginica
148      5.9      3.0      5.1      1.8  Iris-virginica

[149 rows x 5 columns]


# Task1

In [3]:
x=df.iloc[:,0:-1].values # 4 features
y=df.iloc[:,-1].values
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)
cls=SVC()
cls.fit(x_train,y_train)
y_pred=cls.predict(x_test)

sep_len=input("Enter sep_len: ")
sep_wid=input("Enter sep_wid: ")
pet_len=input("Enter pet_len: ")
pet_wid=input("Enter pet_wid: ")
result=cls.predict([[sep_len,sep_wid,pet_len,pet_wid]])
print("predicted class is : "+str(result))


Enter sep_len: 4.7
Enter sep_wid: 3.1
Enter pet_len: 1.4
Enter pet_wid: 2.3
predicted class is : ['Iris-setosa']


In [5]:
print("confusion_matrix \n\n ",confusion_matrix(y_test,y_pred))
print("\n classification_report \n\n",classification_report(y_test,y_pred))

confusion_matrix 

  [[13  0  0]
 [ 0 14  0]
 [ 0  1 10]]

 classification_report 

                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.93      1.00      0.97        14
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        38
      macro avg       0.98      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38



# Task2

In [6]:
x=df.iloc[:,0].values # sep-len
y=df.iloc[:,1].values # sep-wid
corr=np.corrcoef(x,y)
print("corrcoaf between sep-len & sep-wid: \n\n",corr)

corrcoaf between sep-len & sep-wid: 

 [[ 1.         -0.10378415]
 [-0.10378415  1.        ]]


In [7]:
x=df.iloc[:,0].values # sep-len
y=df.iloc[:,2].values # pet-len
corr=np.corrcoef(x,y)
print("corrcoaf between sep-len & pet-len: \n\n",corr)

corrcoaf between sep-len & pet-len: 

 [[1.         0.87128294]
 [0.87128294 1.        ]]


In [8]:
x=df.iloc[:,0].values # sep-len
y=df.iloc[:,3].values # pet-wid  
corr=np.corrcoef(x,y)
print("corrcoaf between sep-len & pet-wid : \n\n",corr)

corrcoaf between sep-len & pet-wid : 

 [[1.         0.81697087]
 [0.81697087 1.        ]]


In [12]:
# we will use pet-len to predict sep-len 
  #  Linear Regression Model to predict sep-len 
    
       # x----> pet-len
       # y-----> sep-len
    # building model 
x=df.iloc[:,2].values # pet-len
y=df.iloc[:,0].values # sep-len

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

x_train=x_train.reshape(-1,1)
x_test=x_test.reshape(-1,1)
y_train=y_train.reshape(-1,1)
y_test=y_test.reshape(-1,1)

lin_reg=LinearRegression() 
lin_reg.fit(x_train,y_train)

# classification model

sep_wid=float(input("Enter sep_wid: "))
pet_len=float(input("Enter pet_len: "))
pet_wid=float(input("Enter pet_wid: "))

sep_len_pred=lin_reg.predict(np.array(pet_len).reshape(-1, 1))  # Expected 2D array

result=cls.predict([[sep_len_pred[0,0],sep_wid,pet_len,pet_wid]])

print("sep_len_pred :",sep_len_pred[0,0])
print("predicted class is : ",result[0])

Enter sep_wid: 3.0
Enter pet_len: 1.4
Enter pet_wid: 0.2
sep_len_pred : 4.8619780674455795
predicted class is :  Iris-setosa


# Task3

In [10]:
# use sep_wid to find sep_len 
x=df.iloc[:,1].values # sep-wid
y=df.iloc[:,0].values # sep_len
corr=np.corrcoef(x,y)
print("corrcoaf between sep-wid & sep_len: \n\n",corr)

corrcoaf between sep-wid & sep_len: 

 [[ 1.         -0.10378415]
 [-0.10378415  1.        ]]


In [13]:
# we will use sep_wid to find sep_len 
  #  Linear Regression Model to predict sep-len from sep-wid
    
       # x----> pet-len
       # y-----> sep-len
    # building model 
x=df.iloc[:,1].values # sep_wid
y=df.iloc[:,0].values # sep-len

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

x_train=x_train.reshape(-1,1)
x_test=x_test.reshape(-1,1)
y_train=y_train.reshape(-1,1)
y_test=y_test.reshape(-1,1)

lin_reg=LinearRegression() 
lin_reg.fit(x_train,y_train)


sep_wid=float(input("Enter sep_wid: "))
pet_len=float(input("Enter pet_len: "))
pet_wid=float(input("Enter pet_wid: "))

sep_len_pred=lin_reg.predict(np.array(sep_wid).reshape(-1, 1))  # Expected 2D array

result=cls.predict([[sep_len_pred[0,0],sep_wid,pet_len,pet_wid]])
print("sep_len_pred :",sep_len_pred[0,0])
print("predicted class is : ",result[0])

Enter sep_wid: 3.0
Enter pet_len: 1.4
Enter pet_wid: 0.2
sep_len_pred : 5.881045193855513
predicted class is :  Iris-setosa


In [14]:
# we will use pet_wid to find pet_len
  #  Linear Regression Model to predict pet-len from pet-wid
    
       # x----> pet-wid
       # y-----> pet-len
    # building model 
x=df.iloc[:,3].values # pet_wid
y=df.iloc[:,2].values # pet-len

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

x_train=x_train.reshape(-1,1)
x_test=x_test.reshape(-1,1)
y_train=y_train.reshape(-1,1)
y_test=y_test.reshape(-1,1)

lin_reg=LinearRegression() 
lin_reg.fit(x_train,y_train)

sep_len=float(input("Enter sep_len: "))
sep_wid=float(input("Enter sep_wid: "))
pet_wid=float(input("Enter pet_wid: "))

pet_len_pred=lin_reg.predict(np.array(pet_wid).reshape(-1, 1))  # Expected 2D array

result=cls.predict([[sep_len,sep_wid,pet_len_pred[0,0],pet_wid]])
print("pet_len_pred :",pet_len_pred[0,0])
print("predicted class is : ",result[0])

Enter sep_len: 4.9
Enter sep_wid: 3.0
Enter pet_wid: 0.2
pet_len_pred : 1.526854741011012
predicted class is :  Iris-setosa
