In [3]:
# 01. Read two strings from user then concatenate them and store the concatenation in string:

str0 = input("Enter first str : ")
str1 = input("Enter second str : ")                                                                      
str2 = str0 +' '+ str1
str2

'amal taha'

In [3]:
# 02. Read string from user then converts the first character to upper case:

str = input("Enter str : ")
res=str.capitalize()
res

Enter str : amal


'Amal'

In [4]:
# 03. Read string from user then convert this string to lower case:

str = input("Enter str : ")
res=str.lower()
res

Enter str : AMAL


'amal'

In [5]:
# 04. Read string from user then convert this string to upper case:

str = input("Enter str : ")
res=str.upper()
res

Enter str : amal taha 


'AMAL TAHA '

In [7]:
# 05. Read string from user then enter character and show if this string contains
# this character or no and if yes show its index in string:
str = input("Enter str : ")
char = input("Enter char : ")
if char in str:
    index = str.index(char)
    print(index)
else:
    print("This char isn't exist")

Enter str : amal
Enter char : f
This char isn't exist


In [8]:
# 06. Read string from user then replace each space ' ' by comma ',':
str = input("Enter str : ")
res=str.replace(' ',',')
print(res)

Enter str : eng amal taha 
eng,amal,taha,


In [9]:
# 07. Read string from user then convert the first character of each word to upper case:
import string
str = input("Enter str : ")
string.capwords(str)

Enter str : amal taha shaaban


'Amal Taha Shaaban'

In [10]:
# 08. Read string from user then replace each comma by ',' by astrisk '*':
str = input("Enter str : ")
res=str.replace(',','*')
print(res)

Enter str : amal,taha,shaaban
amal*taha*shaaban


In [11]:
# 09. Read string from user then remove all spaces at the first and the last:
str = input("Enter str : ")
res=str.strip() 
print(res)

Enter str :    aml taha shaaban  
aml taha shaaban


In [12]:
# 10. Read string from user then convert string to list by splitting string after each space:
import string
str = input("Enter str : ")
str_list=str.split()
print(str_list)

Enter str : amal taha shaaban
['amal', 'taha', 'shaaban']


In [15]:
# 11. Read string and check if this string starts with vowel or not:
str = input("Enter str : ")
str_res=str.upper()
if str_res[0] in ['A', 'E', 'I', 'O', 'U']:
    print ("vowel")
else:
    print ("not vowel")

Enter str : hano
not vowel


In [19]:
# 12. Read list from user then sort this list:
lst=[]
n=int(input("enter numbers of elements : "))
for i in range(0,n):
    element=int(input(""))
    lst.append(element)
    lst.sort()
lst

enter numbers of elements : 3
5
6
3


[3, 5, 6]

In [22]:
# 13. Read list from user then get the second-to-last number in the list: -----> slicing
lst=[]
n=int(input("enter numbers of elements : "))
for i in range(0,n):
    element=int(input())
    lst.append(element)
lst[1:]


enter numbers of elements : 5
3
4
5
6
7


[4, 5, 6, 7]

In [23]:
# 14. Read list of degrees and find the max degree in this list:
lst=[]
n=int(input("enter numbers of elements : "))
for i in range(0,n):
    element=int(input())
    lst.append(element)

y=max(lst)
y


enter numbers of elements : 3
30
50
70


70

In [52]:
# 15. Read list of words and find longest word :

def find_longest_word(word_list):
    longest_word = ""
    for word in word_list:
        if len(word) > len(longest_word):
            longest_word = word
    return longest_word

words_input = input("Enter a list of words: ")
word_list = words_input.split(" ")
longest_word = find_longest_word(word_list)

print(longest_word)


Enter a list of words: amal taha shaaban
shaaban


In [26]:
# 16. Read list and append any item to this list :
lst=[]
n=int(input("enter numbers of elements : "))
for i in range(0,n):
    element=int(input())
    lst.append(element)
lst

enter numbers of elements : 3
4
5
6


[4, 5, 6]

In [27]:
# 17. Read list from user then give user the apility to remove item with the specified value : 
lst=[]
n=int(input("enter numbers of elements : "))
for i in range(0,n):
    element=int(input())
    lst.append(element)

item=int(input("enter item you want to remove"))
if item in lst:
    lst.remove(item)
lst

enter numbers of elements : 3
4
6
7
enter item you want to remove7


[4, 6]

In [28]:
# 18. Write a Python program to convert a list to a tuple :
lst=[1,2,3]
tup=tuple(lst)
tup

(1, 2, 3)

In [29]:
# 19. Write a Python program to reverse a tuple:
tup=(1,2,3,4)
rev_tup=tup[::-1]
rev_tup

(4, 3, 2, 1)

In [30]:
# 20. Write a python program to find size of set:
st=(1,2,3,4)
res_st=len(st)
res_st

4

In [33]:
# 21. Write a program to Read list from user then print distinct items in this list:
lst=[]
n=int(input("enter numbers of elements : "))
for i in range(0,n):
    element=int(input())
    lst.append(element)

unique_lst =[]
for x in lst:
    if x not in unique_lst:
        unique_lst.append(x)
for x in unique_lst:
    print("distinct items :",x)

enter numbers of elements : 3
1
2
1
distinct items : 1
distinct items : 2


In [34]:
# 22. Write a program to find sum of all items in tuples:
tup=(1,2,3,4,80,10)
sum=0
for i in tup:
    sum+=i
sum

100

In [35]:
# 23. Write a program Removes all the elements from the list:
lst=[1,2,3,4,7]
lst.clear()
lst

[]

In [36]:
# 24. Write a program to print dictionary values without keys:
dic={
    1:'Aml',
    2:'Baba',
    3:'somaya'
}
dic.values()

dict_values(['Aml', 'Baba', 'somaya'])

In [37]:
# 25. Write a program to print dictionary keys only:
dic={
    1:'Aml',
    2:'Baba',
    3:'somaya'
}
dic.keys()

dict_keys([1, 2, 3])

In [38]:
# 26. Write a program to print a specefic item by key:
dic={
    1:'Aml',
    2:'Baba',
    3:'somaya'
}
dic[2]

'Baba'

In [39]:
# 27. Write a Python program to remove duplicates from Dictionary:
dic={
    1:'Aml',
    2:'Baba',
    3:'somaya',
    4:'mama',
    2:'hano',
    1:'Aml'
}
dic.items()

dict_items([(1, 'Aml'), (2, 'hano'), (3, 'somaya'), (4, 'mama')])

In [40]:
# 28. Write a Python program to check a dictionary is empty or not:
dic={'A':'Aml','B':'Baba'}
if (len(dic) == 0): 
    print("empty")
else:
    print("not")

not


In [42]:
# 29. Write a NumPy program to create an array of 10 zeros and 10 ones:
import numpy as np
a_zeros=np.zeros(10)
a_ones=np.ones(10)
print(a_zeros)
print(a_ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [45]:
# 30. Write a NumPy program to generate a random number between 0 and 1:
a=np.random.random()
a


0.6147550777659982

In [46]:
# 31. Write a NumPy program to create an array of the integers from 30 to 70.
a=np.arange(30,70).reshape(5,8)
a

array([[30, 31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67, 68, 69]])

In [4]:
# testing
print("amal ")

amal 
