In [2]:
import pandas as pd
import numpy as np 
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest


In [14]:
data='dataset/sport4.csv'
df=pd.read_csv(data,header=None)
df.columns =['Height', 'weight','Age','class']
print(df)

     Height  weight  Age   class
0       170      75   26  basket
1       194      91   35  basket
2       191      95   36  basket
3       196      93   36  basket
4       195      88   37  basket
..      ...     ...  ...     ...
595     165     111   17    sumo
596     156     119   27    sumo
597     169     121   15    sumo
598     153     125   26    sumo
599     154     103   24    sumo

[600 rows x 4 columns]


In [15]:
array=df.values

In [16]:
array.shape

(600, 4)

In [17]:
x=array[:,0:3] # 0 1 2 
y=array[:,3] 
chi=SelectKBest(score_func=chi2,k=2)
fit=chi.fit(x,y)
np.set_printoptions(precision=1) # كام رقم عشري 
print('fit scores : ')
print(fit.scores_)
x_sel=fit.transform(x) # ---> x_sel (subset)
print(x.shape)
print(x_sel.shape)

fit scores : 
[ 387.8 3026.   390.5]
(600, 3)
(600, 2)


In [18]:
# part of them 
print(x[:5,:])
print(x_sel[:5,:])

[[170 75 26]
 [194 91 35]
 [191 95 36]
 [196 93 36]
 [195 88 37]]
[[75 26]
 [91 35]
 [95 36]
 [93 36]
 [88 37]]


In [19]:
# save dataset
z = np.array([x_sel[:, 0], x_sel[:, 1],y])
z = z.T
np.savetxt('dataset/selected_sport.csv', z, delimiter=',',fmt='%1.2f,%1.2f,%s')
print('File saved successfully ')

File saved successfully 
